### ISSUE TITLE
Kaputter Satz bei Mixed Max Cut

### ISSUE THREAD

**Issue by m1cm1c** [jGleitz/AfpG-Skript#10]
```
\begin_inset Formula $M^{*}$
\end_inset

 kann zu 
\begin_inset Formula $M$
\end_inset

 erweitert werden, im ersten Fall die Kante, die die beiden ungematchten
 Knoten in 
\begin_inset Formula $\Delta_{v^{*}}$
\end_inset

verbindet, im zweiten Fall keine Kante hinzugefügt wird.
```

(https://github.com/jGleitz/AfpG-Skript/blob/7c7ad4e93dea89234b63b2015dfcd681453c259a/Inoffizielles%20Skript.lyx#L13801)

Da ist ein kaputter Satz, aber ich bin mir nicht 100% sicher, wie man ihn fixt.

**Comment by jGleitz** [comment]
Ich habe mich nicht wieder eingelesen, um den Kontext zu bekommen. Aber rein basierend darauf, wie ich Sätze baue, bin ich mir ziemlich sicher, dass der Schachtelsatz

> M* kann zu M erweitert werden, **indem** im ersten Fall die Kante, die die beiden
ungematchten Knoten in ∆v* verbindet, im zweiten Fall keine Kante hinzugefügt wird.

gemeint war. Ergibt das Sinn?

**Comment by m1cm1c** [comment]
Sehr gut. Das ist nämlich gleichbedeutend mit der Änderung, die ich mit 95% Wahrscheinlichkeit gemacht hätte, müsste ich eine machen. Ich packe das in meinen Sammel-PR für kleinere Änderungen.
